version: '3.8'

services: # 도커 컴포즈 파일에서 서비스 설정(컨테이너를 서비스로 본다)
  # 주석에 my_server라고 적어주셨지만, 서비스 이름은 my_nginx로 잘 설정되어 있습니다.
  # 실제 컨테이너 이름은 '프로젝트폴더명-my_nginx-1'과 같이 생성됩니다.
  my_nginx: 
    build:
      context: ./nginx # 이미지 빌드에 사용할 Dockerfile이 있는 디렉토리 (정확합니다)
    ports:
      - "8080:80"   # 외부 8080 포트 -> 컨테이너 내부 80 포트 (HLS/헬스 체크용)
      - "1935:1935" # 외부 1935 포트 -> 컨테이너 내부 1935 포트 (RTMP 수신용) [이 부분 추가!]
    restart: always # 컨테이너가 예기치 않게 종료되면 항상 재시작
